// src/components/Navbar.vue
<template>
    <div class="bg-red-700 text-black flex justify-between items-center p-2 px-4 uppercase">
        <div class="flex flex-col text-center font-bold">
            <a href="/">Culture Pain</a>
            <p class="text-sm text-white tracking-widest">Terville</p>
        </div>
        
        <div class="flex space-x-4 font-bold">
            <a href="/menu">Menu</a>
            <a href="/">Contacts</a>
        </div>
    </div>
</template>

// src/components/Navbar.tsx
import HamburgerButton from "./ui/HamburgerButton";
import SearchBar from "./ui/SearchBar";

const Navbar = () => {
  return (
    <div className='flex items-center justify-between p-4 bg-gray-100'>
        <div className='flex'>
            <HamburgerButton />
            <h1>Culture Terville</h1>
            
        </div>
        <div>
            <SearchBar />
        </div>
    </div>
  )
}

export default Navbar
